version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - AZURE_DEVOPS_PAT=${AZURE_DEVOPS_PAT}
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
